### ISSUE TITLE
Cannot start imm2virtual.exe

### ISSUE THREAD

**Issue by Fake4d** [nannib/Imm2Virtual#5]
It is not possible for me to start the new version in my internal lab.. I have tried three computers with the newest windows 10 
Betriebsystemname       Microsoft Windows 10 Pro
Version 10.0.17134 Build 17134

I get the following (german) error message:

![reference](https://user-images.githubusercontent.com/11659893/40357442-79d34a8c-5dbc-11e8-8406-196b1819a248.PNG)

I think it is trying to get the validation of the signature from a server.. Is there a new requirement? The old version was working fine. 

Do you have any ideas?

**Comment by roswitina** [comment]
It's the same with me.

**Comment by nannib** [comment]
Try now! and let me know! :-)
Thanks

**Comment by Fake4d** [comment]
Thank you ! Working fine again for me!
